# Generated by Django 4.0.2 on 2022-05-04 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babarkotapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Briliant_Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('standard', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=50)),
                ('achievement', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Gal_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='General_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_year', models.CharField(max_length=50)),
                ('lang', models.CharField(max_length=50)),
                ('gr_number', models.IntegerField()),
                ('udise', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=50, null=True)),
                ('religion', models.CharField(max_length=100)),
                ('birth_place', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('dob_in_words', models.CharField(max_length=50)),
                ('previous_school_std', models.TextField()),
                ('school_joining', models.CharField(max_length=50)),
                ('admission_std', models.CharField(max_length=50)),
                ('fees', models.CharField(max_length=50, null=True)),
                ('date_leaving', models.CharField(max_length=50, null=True)),
                ('leaving_std', models.CharField(max_length=50, null=True)),
                ('leaving_reason', models.TextField(null=True)),
                ('progress', models.CharField(max_length=50, null=True)),
                ('behaviour', models.CharField(max_length=50, null=True)),
                ('date_taking_lc', models.CharField(max_length=50, null=True)),
                ('note', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword_Defination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('lang', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Noticeboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=50)),
                ('qoute', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='school_speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('standard', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('cast', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=50)),
                ('udise', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Useful_Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='Role',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='category',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='poority_line',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='teacher_code',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='uside_code',
        ),
        migrations.AddField(
            model_name='user_details',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.CreateModel(
            name='Grant_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_no', models.IntegerField(unique=True)),
                ('grant_details', models.TextField()),
                ('amount', models.CharField(max_length=50)),
                ('order_no', models.CharField(max_length=100)),
                ('bank_deposite_date', models.DateField()),
                ('remarks', models.TextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babarkotapp.account_model')),
            ],
        ),
        migrations.CreateModel(
            name='General_Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_no', models.IntegerField()),
                ('date', models.DateField()),
                ('particulars', models.TextField()),
                ('credit', models.CharField(max_length=50)),
                ('debit', models.CharField(max_length=50)),
                ('credit_bal', models.CharField(max_length=50)),
                ('debit_bal', models.CharField(max_length=50, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babarkotapp.account_model')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery')),
                ('desc', models.CharField(max_length=255, null=True)),
                ('css_term', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babarkotapp.gal_category')),
            ],
        ),
        migrations.CreateModel(
            name='Cheque_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_no', models.IntegerField(unique=True)),
                ('date', models.DateField()),
                ('agency_name', models.CharField(max_length=255)),
                ('purchase_detail', models.CharField(max_length=255)),
                ('bill_no', models.CharField(max_length=50)),
                ('cheque_no', models.CharField(max_length=100)),
                ('cheque_date', models.DateField()),
                ('amount', models.CharField(max_length=50)),
                ('paying_amount', models.CharField(max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babarkotapp.account_model')),
            ],
        ),
        migrations.CreateModel(
            name='Cash_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_no', models.IntegerField()),
                ('date', models.DateField()),
                ('name_and_particulars', models.TextField()),
                ('reciept', models.CharField(blank=True, max_length=50, null=True)),
                ('voucher_no', models.CharField(blank=True, max_length=50, null=True)),
                ('total_amount', models.CharField(max_length=50)),
                ('debit_or_credit', models.CharField(max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babarkotapp.account_model')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babarkotapp.general_ledger')),
            ],
        ),
        migrations.CreateModel(
            name='Bill_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_no', models.IntegerField()),
                ('bill_from', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('bill_voucher', models.CharField(max_length=200)),
                ('bill_amount', models.CharField(max_length=255)),
                ('payable_amount', models.CharField(max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babarkotapp.account_model')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendance', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babarkotapp.student_data')),
            ],
        ),
    ]
